src/Hub.php
src/HubServiceProvider.php
src/Resources/CompanyResource.php

Buscando uma company segundo o seu UuID

company resouce

---

composer.json
src/Console/InstallHub.php
src/Middleware/AuthenticateHubMiddleware.php

use:
`auth()->user()->can('view-company-bf203b98-94a5-485d-a47a-11d26d260f58)`
return bool
Sugestão, criarmos uma function similar a can, porém, ao inves de retornar bool, dispara uma exception se nao tiver permissao, assim a propria exception poderia disparar um 403 para o usuário

Permissions

---

src/Contracts/Resources/UserResourceContract.php
src/Resources/UserResource.php

User index implementation

---

src/Resources/UserResource.php

users()->getWhereHasPermission() and users()->getWhereBelongsToPermission() implementation

Users resource scopes

---

src/Traits/LoginUser.php

Added syncpermissions to loginuser trait.

Update loginuser trait

---

src/Resources/UserResource.php

Users resource getWhereHasPermission argument fix

Users resource getWhereHasPermission argument fix

---

src/Traits/LoginUser.php

Opção para sincronizar as permissões do usuário já existente no cache.

Update cached user permissions

---

src/Traits/LoginUser.php

Ao atualizar a company do usuário no dashboard do HUB não estava sendo atualizado na tabela `users`.

Fix company update

---

src/Traits/LoginUser.php

**Problema:**
O ajuste que fiz anteriormente para atualizar a company do usuário utilizava o método `getUserCompany()` o qual não é o mais adequado para esse caso. O `getUserCompany()` sempre bate na API do HUB e isso acaba trazendo um pouco de demora nas requests.
**Solução:**
Criação de um método mais adequado para atualizar a company do usuário e somente bater na API do HUB para buscar os dados da company quando não encontrá-la no banco local.

Fix company update performance

---

src/Middleware/AuthenticateCheckHubMiddleware.php

Update authenticate check middleware

Update authenticate check middleware

---

src/Middleware/AuthenticateCheckHubMiddleware.php

Fix md5token

---

src/Resources/CompanyResource.php

Get companies by user permission on programmatic companies index

Get companies by user permission on programmatic companies index

---

src/Traits/LoginUser.php

Super user update fix

---

src/Traits/LoginUser.php

Develop into master

---

src/Resources/UserResource.php
src/Traits/LoginUser.php

Log removal + limit,offset on UserResource permission functions

Log removal + limit,offset on UserResource permission functions

---

src/Entities/HubCompany.php

HubCompany Softdeletes

---

src/Traits/LoginUser.php

User permissions diff fix on /me

User permissions diff fix on /me

---

src/Services/UserCompanyService.php

- Criar método para retornar usuários por cargo
Criação de método para retornar usuários por cargo pela ordem
https://www.notion.so/bildvitta/Criar-fun-o-no-SDK-para-buscar-cargos-por-n-vel-31999b44b2fa4ea48b0e4da26c7d244c

method to get user positions by order

---

src/Services/UserCompanyService.php

Corrigir método por cargos por ordem
Alteração de compan_id ao buscar user companies
https://www.notion.so/bildvitta/Criar-fun-o-no-SDK-para-buscar-cargos-por-n-vel-31999b44b2fa4ea48b0e4da26c7d244c

fixing query user company

---

database/migrations/2023_08_03_184126_create_user_company_real_estate_developments_table.php
src/Entities/HubUserCompany.php
src/Services/UserCompanyService.php

- Erro de nomes de models
- Nomes de função relação no plural
- Tratamentos de exceções
- Alteração de nome de model para singular
- Alteração de nome de função de relação para hasOne
- Criação de exceptions para tratamento de inconscistência de time
https://www.notion.so/bildvitta/Corre-o-de-bug-de-busca-de-cargos-pai-quando-n-o-existe-c5f5784f4adb49ee96d2884559b96808

exceptions when inconsistent team

---

database/migrations/2023_07_12_162137_create_user_companies_table.php

Bug de versão do laravel ao criar uuid default na migration
Inclusão de parâmetro uuid no método q cria o uuid na migration do user_company
https://www.notion.so/bildvitta/Corre-o-de-bug-de-SDK-na-cria-o-de-uuid-para-user-company-59ff6663ab924dc7bc819222b35c5ebc

Feature/next fix UUID

---

src/Services/UserCompanyService.php

Buscar cargos por empresa de forma ordenada
Criação de método getSortedPositions para trazer os cargos por empresa ordenados
https://www.notion.so/bildvitta/Cria-o-de-m-todo-para-trazer-os-cargos-ordenados-no-SDK-e0567122ac4743b08063fd2b4bc4e6d0

get sorted positions

---

src/Traits/User/HasCompanyLinks.php

- Ao usar o **_accessor_** `realEstateDevelopments` da **_trait_** `HasCompanyLinks` vinha com os empreendimentos  vazios.
- Troca do nome do método para `real_estate_developments` que está na model `HubUserCompany` 

Change method name in accessor

---

src/Services/UserCompanyService.php

- Método para checar o cargo do usuário na company
- Criação de método para checar o cargo do usuário na company
https://www.notion.so/bildvitta/Cria-o-de-m-todos-novos-no-UserCompanyService-bf47a96c617842d8b8ac516b07ae3b8c

check position user in company

---

src/Services/UserCompanyService.php

refactore method checkPositionUser

---

src/Services/UserCompanyService.php

including cache to check position user

---

config/hub.php
src/Services/UserCompanyService.php

config model_user_key

---

src/Services/UserCompanyService.php

include only position in show all

---

src/Services/UserCompanyService.php

- Funções para pegar usuários pai
- Funções para pegar usuários pai

create method get parent user

---

src/Services/UserCompanyService.php

including model user key config

---

composer.json

- Testes para utilização do laravel na versão 10.
- Incluído a versão do laravel 10 nos pacotes.

Update to laravel 10;

---

src/Traits/User/HasCompanyLinks.php

- Correção do erro
`SQLSTATE[42P01]: Undefined table: 7 ERROR:  missing FROM-clause entry for table "companies"`
- Alterar a coluna `companies` para `hub_companies` no método `getMainLinkedCompanies`

Change column name;

---

README.md
composer.json
src/Exceptions/HubException.php
src/Http/Controllers/Auth/AuthController.php
src/Http/Controllers/Users/Notifications/NotificationsController.php
src/Http/Controllers/Users/UsersController.php
src/Resources/Resource.php
src/Scopes/Companies/PublicListScope.php

Resolvendo o problema de não exibir as notificações nos outros módulos do nave.
Adicionado o driver do Ably (que é nosso serviço de WebSocket) para funcionar a notificação in app nas aplicações do Nave.
https://www.notion.so/bildvitta/Sprint-18-JUN-2-2024-4c3a1a07b00e4a8b8902397d33ec7d86?p=71433333d4b34b6fb847c56b1ee19a4e&pm=s

Merging develop into master

---

config/hub.php
database/migrations/2024_07_31_124505_iss_sdk_create_brands_table.php
database/migrations/2024_07_31_130241_add_brand_id_on_companies_table.php
src/Entities/HubBrand.php
src/Entities/HubCompany.php
src/Middleware/AuthenticateHubMiddleware1.php
src/Traits/LoginUser.php

Adicionando o gerenciamento de marcas e o vinculo dele com as empresas
Adicionando o gerenciamento de marcas e o vinculo dele com as empresas
https://www.notion.so/bildvitta/AGO-1-2024-Sprint-21-b29118fbb9774d2da09ee6a62874a907?p=ad1a9d5d4d464005b2bbba28067f06b6&pm=s

Gerenciamento de marcas

---

config/hub.php
src/Models/Brand.php
src/Models/Company.php
src/Models/Position.php
src/Models/User.php
src/Models/UserCompany.php
src/Models/UserCompanyParentPosition.php
src/Models/UserCompanyRealEstateDevelopment.php
src/Traits/UsesHubDB.php

DB Connection

---

database/migrations/2024_11_26_165439_add_main_company_on_users_table.php

Add main_company_id foreign key to users table migration

---

src/HubServiceProvider.php

Add Authenticatable contract import in HubServiceProvider

---

README.md
src/Traits/User/HasCompanyLinks.php

Adicionar método de empresas públicas do usuário para recuperar empresas públicas para o usuário

---

src/HubServiceProvider.php
src/Traits/User/HasCompanyLinks.php

Esta solicitação de pull inclui uma pequena alteração no arquivo `src/HubServiceProvider.php`. A alteração adiciona a importação `Illuminate\Support\Arr` ao arquivo.
* [`src/HubServiceProvider.php`](diffhunk://#diff-2a10d96f7172195d740b2b8acbc4ab451ff89d72789fd744b3629f9da1eb1b6cR19): Adicionada a importação `Illuminate\Support\Arr`.

adiciona a importação `Illuminate\Support\Arr` ao arquivo HubServiceProvider

---

src/Traits/User/HasCompanyLinks.php

Add correct Model import

---

src/HubServiceProvider.php
src/Traits/User/HasCompanyLinks.php

Este pull request inclui diversas alterações nos arquivos `src/HubServiceProvider.php` e `src/Traits/User/HasCompanyLinks.php` para aprimorar o registro de erros, refatorar o tratamento de modelos e atualizar a verificação de permissões.
Melhorias no registro de erros e no tratamento de modelos:
* [`src/HubServiceProvider.php`](diffhunk://#diff-2a10d96f7172195d740b2b8acbc4ab451ff89d72789fd744b3629f9da1eb1b6cL12-R20): Adicionadas as importações `Log` e `Str` para aprimorar o registro de erros e o tratamento de strings.
* `public function boot(): void` em `src/HubServiceProvider.php`: Refatorada a lógica de tratamento de modelos para usar uma coleção e adicionado o registro de erros para argumentos nulos e valores não UUID. …

Aprimoramento do registro de erros e atualizar a verificação de permissões

---

README.md
src/HubServiceProvider.php
src/Traits/User/HasCompanyLinks.php

Develop to Master
